org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true

# Environment Properties
minecraft_version=26.2
minecraft_version_range=[26.1,27)
neo_version=26.2.0.67
neo_version_range=[26.1.0, 27.0.0)

## Mod Properties
mod_id=batsremove
mod_name=Bats Remove (NeoForge 26)
mod_license=MIT
mod_version=1.0.1
mod_group_id=com.batsremove

