org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.0,1.21.11)
neo_version=21.1.248
neo_version_range=[21.0.0, 21.11.0)

## Mod Properties
mod_id=batsremove
mod_name=Bats Remove (NeoForge 1.21)
mod_license=MIT
mod_version=1.0.1
mod_group_id=com.batsremove

